CREATE TABLE suburbs (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    minlong DOUBLE PRECISION NOT NULL,
    minlat DOUBLE PRECISION NOT NULL,
    maxlong DOUBLE PRECISION NOT NULL,
    maxlat DOUBLE PRECISION NOT NULL
);
